name: Deploy

on:
  workflow_run:
    workflows: ["Test and Build"]
    types:
      - completed
    branches: [ main, develop ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/develop'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/
        
    # Vercel Deployment
    - name: Deploy to Vercel (Staging)
      if: env.VERCEL_TOKEN != ''
      run: |
        npm install -g vercel
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        
    # Netlify Deployment
    - name: Deploy to Netlify (Staging)
      if: env.NETLIFY_TOKEN != ''
      run: |
        npm install -g netlify-cli
        netlify deploy --prod --dir=dist --token ${{ secrets.NETLIFY_TOKEN }}
        
    # GitHub Pages Deployment
    - name: Deploy to GitHub Pages (Staging)
      if: env.GITHUB_TOKEN != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages-staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files
        path: dist/
        
    # Vercel Deployment
    - name: Deploy to Vercel (Production)
      if: env.VERCEL_TOKEN != ''
      run: |
        npm install -g vercel
        vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
        
    # Netlify Deployment
    - name: Deploy to Netlify (Production)
      if: env.NETLIFY_TOKEN != ''
      run: |
        npm install -g netlify-cli
        netlify deploy --prod --dir=dist --token ${{ secrets.NETLIFY_TOKEN }}
        
    # GitHub Pages Deployment
    - name: Deploy to GitHub Pages (Production)
      if: env.GITHUB_TOKEN != ''
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: gh-pages 